version: '3'

services:
  app:
    build: .
    volumes:
      - ./data/:/data/:rw
    command: sleep infinity

  proxy:
    image: ubuntu/squid
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
